# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage genbadge[all]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-line-length=119 --statistics
    - name: Coverage with pytest
      run: |
        coverage run --omit "tests/*.py" -m pytest ./tests/ --junitxml=./report.xml -s
        coverage report
        coverage xml
        # genbadge tests -i ./report.xml -s -o ./tests.svg
        # genbadge coverage -i ./coverage.xml -s -o ./coverage.svg
    # - name: Setup node
    #   uses: actions/setup-node@v1
    # - name: Upload badge to GitHub
    #   uses: LasyIsLazy/github-upload-action@v0.1.0
    #   with:
    #     access-token: ${{ secrets.ACCESS_TOKEN }}
    #     file-path: coverage.svg
    #     owner: NicolasGrosjean
    #     repo: Paradox_localization_utils 
    #     branch-name: actions
    #     remote-dir: badges
    #     commit-message: Update coverage badge

